# Generated by Django 5.0.1 on 2024-01-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_choices', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('average', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ECTS', models.IntegerField()),
                ('course_type', models.CharField(choices=[('Lec', 'Lecture'), ('Pra', 'Practicals'), ('Lab', 'Laboratory'), ('Pro', 'Project'), ('Sem', 'Seminary')], default='Lec', max_length=3)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.coursegroup')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('field_of_studies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.fieldofstudies')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('week_type', models.CharField(choices=[('every', 'Every week'), ('odd', 'Odd week'), ('even', 'Even week')], default='every', max_length=5)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fr', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('building', models.CharField(max_length=30)),
                ('hall', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.course')),
                ('enrollment_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.enrollmentedition')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.basket')),
                ('group_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.group')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.student'),
        ),
        migrations.CreateModel(
            name='Studying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.fieldofstudies')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.student')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.group')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.student')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.group')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.timetable')),
            ],
        ),
    ]
