# Generated by Django 5.0.1 on 2024-01-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='name',
            field=models.CharField(default='Bazy Danych', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollmentedition',
            name='academic_year',
            field=models.CharField(max_length=15),
        ),
    ]
