# Generated by Django 5.0.1 on 2024-01-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_coursegroup_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.enrollmentedition')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_permitted', models.BooleanField(default=False)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('is_permitted_earlier', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.student')),
                ('queue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.enrollmentqueue')),
            ],
        ),
        migrations.CreateModel(
            name='GridModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.enrollmentedition')),
            ],
        ),
        migrations.CreateModel(
            name='QueueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.enrollmentqueue')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.uniworker')),
            ],
        ),
    ]
